title: Architecture, security & methodologies
date: 22 October
sessions:
  - title: How to set up a secure system.
    description: "My speech will be based on the presentation of IT system security architectures, so I'm going to talk about the cloud and virtualization.
                I will present the Nagios and Proxmox tools."
    startTime: "2020-10-22T18:15:00+01:00"
    endTime: "2020-10-22T18:45:00+01:00"
    speaker:
      name: Mouad Sissani
      role: Security Adviser
      about: "Security adviser and a junior customer care."
      avatar: /speakers/sissank.jpg
  - title: "Introduction to Cyber Security: You'll want to hack after this talk."
    description: "This talk includes :
- Quick Introduction of Information Security (InfoSec, Types of hackers, types of vulnerabilities)
- Different security threats that we're facing on our era.
- In-Depth real life scenarios/examples of security issues that targeted some IoT devices.
- Q&A Session

You can find the the talk slides here : https://www.othmanetamagart.com/Slides/slides-tais.html
P.S : the slides can be later modified/tailored for BlaBLaConf specifically."
    startTime: "2020-10-22T18:50:00+01:00"
    endTime: "2020-10-22T19:20:00+01:00"
    speaker:
      name: Othmane Tamagart
      role:  Information Security Researcher
      about: ""
      avatar: /speakers/tamaghart.jpg
  - title: "Advanced attacks in decentralized applications."
    description: "In this workshop, we will explore the fundamentals of decentralized applications, of the Solidity language as well as the advanced attacks that can affect your Smart contract and how to protect yourself.
                  We will also discuss the tools and techniques for auditing Smarts Contracts and best methods and practices in the secure development of the dAPP"
    startTime: "2020-10-22T19:25:00+01:00"
    endTime: "2020-10-22T20:15:00+01:00"
    speaker:
      name: Souhail Mssassi
      role: CEO of CRISIS
      about: "He is the CEO of CRISIS, he has a 5+ years experience in cybersecurity in offensive security specialized in application security, cryptography and security of decentralized applications.
              He conducted several audit missions, particularly in the banking sector.
              He is also a speaker and he presented Security lectures in schools as well as universities in Morocco.
              In parallel, he does research in the field of security lately in Formal Verification."
      avatar: /speakers/mssassi.png
  - title: "Android Security: An In-depth Analysis of Access Control Policies in Android Firmwares and Linux Kernel."
    description: "What I will be covering?
                In this talk, I will be talking about the internals of the security of Android operating system from a firmware perspective. I will be presenting how access control mechanisms are designed in this large system and how to find inconsistencies that can lead to zero-day exploits in vendors' firmwares. I will also show that many vendors' apps are vulnerable to various security issues. My talk is all backed up by the official Android documentation and the research that I am doing in my PhD in this field.

                Does the talk include Demo?
                For the moment no because I am still working on a tool to automate the process and I don't think (for the moment) that it will be open source.

                How participants will benefit from your talk?
                Participants will get an idea of how Android run their applications and how it ensures a decent level of security for the user from a low level perspective. In addition, they will get an idea of how to find zero-day vulnerabilities in Android by finding inconsistencies in access control policies."
    startTime: "2020-10-22T20:20:00+01:00"
    endTime: "2020-10-22T20:50:00+01:00"
    speaker:
      name: Ahmed Lekssays
      role: Phd Researcher
      about: "I am 24 years old. I got a masterâ€™s degree in Software Engineering from at Al Akhawayn University in Ifrane, Morocco. I am currently pursuing a PhD degree in Computer Security at the University of Insubria in Varese, Italy under the Marie-Curie Fellowship. I am a cybersecurity analyst and an enthusiast of computer science. I am an ex-champion of ACM MCPC twice, and I have been acknowledge by several companies for finding security issues in their applications such as WhatsApp and Microsoft."
      avatar: /speakers/lekssays.jpg
  - title: Container supply chain security
    description: "In this talk we will explore the concepts of containers security, from build to deployment. We will look at some of the popular tools and cloud products that allow to scan images when they are built, find vulnerabilities and flag them and how can configure you CI/CD pipeline to be as secure as possible."
    startTime: "2020-10-22T20:55:00+01:00"
    endTime: "2020-10-22T21:25:00+01:00"
    speaker:
      name: Abdellfetah Sghiouar
      role: Google Cloud Engineer
      about: "Google Cloud engineer working on Google Cloud Platform and all cloud stuff, specializes and work mainly on k8s, containers, istio and all the cool stuff"
      avatar:  /speakers/abdel.jpg
  - title: Tools & Methods to Grow!
    description: "What is SaaS? and Why developers should adopt SaaS business model instead of software traditional business model (On-Premise Softwares). This will be a short, but rich session to introduce you to the SaaS basics"
    startTime: "2020-10-22T21:30:00+01:00"
    endTime: "2020-10-22T21:45:00+01:00"
    speaker:
      name: Ayoub Moustaid
      role: CEO of ODS
      about: "Let's discover some of the most useful tools & methods, you should absolutely know to help you grow in the digital era"
      avatar: /speakers/moustaid.jpg
